name = "dchelloword"
description = "Shiny new project"
version = "0.1.0-dev"

authors = ["Marc"]
maintainers = ["Marc <dkm@kataplop.net>"]
maintainers-logins = ["dkm"]

executables = ["dchelloword"]

[[depends-on]]
bare_runtime = "*"


[[pins]]
bare_runtime = { path='../bare_runtime' }

[build-switches]
release.optimization = ["-gnat2022"]
development.optimization = ["-gnat2022", "-g3", "-O0"]

[gpr-set-externals]
BARE_RUNTIME_SWITCHES = "-fomit-frame-pointer -ml -m4-single-only -ffunction-sections -fdata-sections -matomic-model=soft-imask -ftls-model=local-exec"
